version: "3"
services:

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
    ports:
      - "9200:9200"
    networks:
      - elasticnet
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    networks:
      - elasticnet
    volumes:
      - esdata2:/usr/share/elasticsearch/data

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    networks:
      - elasticnet
    volumes:
      - esdata3:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch1:9200
    ports:
      - 5601:5601
    networks:
      - elasticnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  elasticnet: